### ISSUE TITLE
Does Answer Set Programming belong in this list?

### ISSUE THREAD

**Issue by luketpeterson** [newca12/awesome-rust-formalized-reasoning#1]
The work by the Potasco group seems highly relevant.
https://potassco.org/
https://github.com/potassco

It's not Rust native, but there are sporadically maintained Rust bindings.
https://crates.io/crates/clingo

**Comment by lorenzleutgeb** [comment]
IMO yes. Should be in [*Bindings*](https://github.com/newca12/awesome-rust-formalized-reasoning?tab=readme-ov-file#bindings).

**Comment by newca12** [comment]
Sure, definitely relevant. Thanks. Fixed in 0073105
